import NavigationBar from "@/components/core/NavigationBar";
import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CapacitorPwaLoader } from "@/components/utility/CapacitorPwaLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"
      ></meta>
      <body
        className={`flex flex-col h-screen ${inter.className}`}
      >
        <main className="h-full">
          {children}
          <CapacitorPwaLoader />
        </main>
      </body>
    </html>
  );
}
