import NavigationBar from "@/components/core/NavigationBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col w-full min-h-screen ${inter.className}`}>
        <main className="relative flex flex-col flex-1 items-center">
          {children}
        </main>
        <footer>
          <NavigationBar></NavigationBar>
        </footer>
      </body>
    </html>
  );
}
