import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header></header>
      <body className={inter.className}>
        <main className="flex flex-col items-center min-h-screen">
          {children}
        </main>
      </body>
      <footer></footer>
    </html>
  )
}
