name: Test Build

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*", "latest"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v5
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
